#lang racket/base
(require "parameter.rkt")

(provide char-delimiter?)

(define (char-delimiter? ec config)
  (or (not (char? ec))
      (char-whitespace? ec)
      (char=? ec #\()
      (char=? ec #\))
      (char=? ec #\[)
      (char=? ec #\])
      (char=? ec #\{)
      (char=? ec #\})
      (char=? ec #\')
      (char=? ec #\`)
      (char=? ec #\,)
      (char=? ec #\;)
      (char=? ec #\")
      (and (char=? ec #\.)
           (check-parameter read-cdot config))))
