
(define extfl-table
  (make-primitive-table
   extflmin
   extflatan
   extfl+
   extflmax
   extflfloor
   extfl<=
   extflvector
   extfl->floating-point-bytes
   extfltruncate
   ->extfl
   extflsin
   extflonum?
   extflacos
   extflvector-ref
   extflexp
   extflabs
   extflonum-available?
   extfl<
   extfl->exact
   extfl->fx
   extfl->inexact
   extflvector-set!
   make-extflvector
   extflcos
   extflvector-length
   extfl/
   extflceiling
   floating-point-bytes->extfl
   extfl>=
   make-shared-extflvector
   extflround
   extfl->exact-integer
   real->extfl
   extflexpt
   fx->extfl
   shared-extflvector
   extfl>
   extfllog
   extflvector?
   extfl=
   extflsqrt
   extfl*
   extfl-
   extfltan
   extflasin))
